apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: app-git
spec:
  source:
    git:
      uri: https://github.com/CamilaHirschf/App.git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.8
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: app-git:latest
