apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-git
  template:
    metadata:
      labels:
        app: app-git
    spec:
      containers:
      - name: app-git
        image: app-git:latest
        ports:
        - containerPort: 5000
