apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app-git
spec:
  host: app-git-app-flask.apps.ocpd.anses.gov.ar
  to:
    kind: Service
    name: app-git
  port:
    targetPort: 8080
  wildcardPolicy: None
